@startuml Wallet

title Wallet

state Initial <<fork>>
note right of Initial
  Wallet and Currency requests run
  in parallel. Wallet results are only
  visible whenCurrencystate is success
end note
state ReadCurrenciesUninitialized
state ReadCurrenciesLoading
state ReadCurrenciesError
state ReadCurrenciesSuccess {
  state ReadCurrenciesEntry <<entryPoint>>
  state ReadWalletUninitialized
  state ReadWalletLoading
  state ReadWalletError
  state ReadWalletSuccess

  ReadWalletUninitialized --> ReadWalletLoading : trigger
  ReadWalletLoading --> ReadWalletError : rejected
  ReadWalletLoading --> ReadWalletSuccess : fulfilled
}

[*] --> Initial : mount

Initial --> ReadCurrenciesUninitialized
Initial --> ReadWalletUninitialized
ReadCurrenciesUninitialized --> ReadCurrenciesLoading : trigger
ReadCurrenciesLoading --> ReadCurrenciesError : rejected
ReadCurrenciesLoading --> ReadCurrenciesEntry : fulfilled

@enduml