@startuml

title Shared Inventory UI States

state Initial
Initial : readAccountInventory.isUninitialized = true
Initial : readItems.isUninitialized = true
Initial --> AccountInventoryLoading : readAccountInventory() loading

state AccountInventoryLoading
AccountInventoryLoading : readAccountInventory.isLoading = true
AccountInventoryLoading : readItems.isUninitialized = true
AccountInventoryLoading --> AccountInventoryError : readAccountInventory() error
AccountInventoryLoading --> AccountInventorySuccess : readAccountInventory() success

state AccountInventoryError
AccountInventoryError : readAccountInventory.isError = true
AccountInventoryError : readAccountInventory.isFetching = true | false
AccountInventoryError : readItems.isUninitialized = true
AccountInventoryError --> AccountInventorySuccess : readAccountInventory() success
AccountInventoryError -> AccountInventoryError : readAccountInventory() error

state AccountInventoryDirtyError
AccountInventoryDirtyError : readAccountInventory.isError = true
AccountInventoryDirtyError : readAccountInventory.isFetching = true | false
AccountInventoryDirtyError : readItems = any
AccountInventoryDirtyError --> AccountInventorySuccess : readAccountInventory() success
AccountInventoryDirtyError --> AccountInventoryDirtyError : readAccountInventory() error

state AccountInventorySuccess {
  [*] --> ItemsInitial
  state ItemsInitial
  ItemsInitial : readItems.isUninitialized = true
  ItemsInitial : readItems.isFetching = false
  ItemsInitial --> ItemsLoading : readItems() loading
  
  state ItemsLoading
  ItemsLoading : readItems.isLoading = true
  ItemsLoading : readItems.isFetching = false
  ItemsLoading --> ItemsSuccess : readItems() success
  ItemsLoading --> ItemsError : readItems() error
  
  state ItemsError
  ItemsError : readItems.isError = true
  ItemsError : readItems.isFetching = true | false
  ItemsError --> ItemsSuccess : readItems() success
  ItemsError --> ItemsError : readItems() error
  
  state ItemsSuccess
  ItemsSuccess : readItems.isSuccess = true
  ItemsSuccess : readItems.isFetching = true | false
  ItemsSuccess --> ItemsSuccess : readItems() success
  ItemsSuccess --> ItemsError : readItems() error
}
AccountInventorySuccess : readAccountInventory.isSuccess = true
AccountInventorySuccess : readAccountInventory.isFetching = true | false
AccountInventorySuccess : readItems = any
AccountInventorySuccess --> AccountInventorySuccess : readAccountInventory() success
AccountInventorySuccess -> AccountInventoryDirtyError : readAccountInventory() error


@enduml